CREATE TABLE "im_keyword_adr" (keyword text, lang_id integer, id integer NOT NULL PRIMARY KEY AUTOINCREMENT, parent_id integer DEFAULT 0, depth integer);
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'AEMTER','1','1','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Firmen','1','2','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Handwerker','1','8','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'DIENSTLEISTER','1','20','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Oliver','1','24','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Rabten Choeling','1','37','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Rabten Stiftung','1','38','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Alle Adressen','1','58','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Informatik','1','64','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Steiner Schule','1','75','0','1' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Möbel','1','3','2','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Transport','1','4','2','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Treuhand','1','5','2','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Versicherungen','1','6','2','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Yakzüchter','1','7','2','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Sanitätshaus','1','62','2','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Online Shop','1','82','2','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Autogarage','1','9','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Cheminée','1','10','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Diverse','1','11','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Elektriker','1','12','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Ferblanterie','1','13','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Gipser Maler','1','14','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Heizung','1','15','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Kaminfeger','1','16','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Maurer','1','17','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Menuiserie charpente','1','18','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Sanitär','1','19','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Schwimmbad','1','86','8','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Oel','1','21','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Supercard','1','22','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Swisscom','1','23','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Bank','1','53','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Coiffeur','1','57','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Telefon','1','61','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Elektro Inspektion','1','66','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Familienunterstützung','1','71','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Presse','1','73','20','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Arzt','1','25','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Behörden','1','27','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Freunde','1','28','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'GFK','1','29','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Hausverwaltung','1','30','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Hotels','1','31','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Restaurants','1','32','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Verwandte','1','33','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Steiner Schule','1','52','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Betatest Cashbook.Pro','1','56','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Kreditkarten','1','67','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Ricardo / Ebay','1','72','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Versicherung','1','87','24','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Heiler','1','26','25','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Physio','1','74','25','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Spitex / CMS','1','84','25','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Osswald','1','34','33','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Simon','1','35','33','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Familie','1','85','33','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Paten','1','36','35','4' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Comité','1','39','37','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Fiduciaire','1','40','37','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Internet','1','41','37','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Anwalt','1','42','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Architekt','1','43','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Bank','1','44','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Geschichte','1','45','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Interessenten','1','46','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Mongolei','1','47','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Notar Treuhand','1','48','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Pächter','1','49','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Tassonneyres','1','50','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Zimmer','1','51','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Steuern VD','1','59','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Versicherung','1','65','38','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Nachbarn','1','60','50','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Seminar.pro','1','83','64','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( '2015/16','1','81','75','2' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Eltern','1','76','81','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Lehrer','1','77','81','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Klasse 3a','1','79','81','3' );
INSERT INTO "im_keyword_adr" ( "keyword","lang_id","id","parent_id","depth" ) VALUES ( 'Mailing Fragebogen Jan-2016','1','80','81','3' );
